### ISSUE TITLE
Check UCS2 vs UCS4

### ISSUE THREAD

**Issue by rmcgibbo** [manylinux/auditwheel#8]
For Py < 3.2, the manylinux1 policy requires building against UCS4 Python, so we have to check for this in extensions modules by looking through the symbol table for the use of any `PyUnicodeUCS2_*` functions, and give a helpful error message.

**Comment by njsmith** [comment]
I just built UCS2 and UCS4 versions of 2.7 to check, and can confirm that yeah, the only differences in the exported symbols are that UCS2 builds export a bunch of `PyUnicodeUCS2_*` and `_PyUnicodeUCS2_*` functions, and UCS4 builds do not.

**Comment by rmcgibbo** [comment]
Well, the other difference is that the UCS4 builds export `PyUnicodeUSC4_*` symbols. But yeah, to implement this, I'm going to do the Python equivalent of

`readelf --dyn-syms <extension.so> | grep PyUnicodeUCS4 | wc`

**Comment by njsmith** [comment]
Oh, sure, but "not using UCS4" is fine, it's "using UCS2" that's bad :-)

**Comment by njsmith** [comment]
(Speaking of which I assume in your comment that's a typo and you mean UCS2 in the grep command.)

**Comment by rmcgibbo** [comment]
Yeah, I edited it right after posting it.

**Comment by njsmith** [comment]
Ah-hah, the edit just didn't propagate to my screen. It's very confusing how some parts of github pages automatically update as things change, and some parts just go stale :-(
